// lexicon.js – Kuratiertes Keyword-Lexikon für das Auto-Tagging.
// Muster sind gegen die echten Vortragstitel verifiziert (tools/verify_lexicon.mjs).
// Matching: Teilstring auf normalisiertem Titel (klein, ohne Diakritika-Faltung
// bei Kyrillisch; Latein wird gefaltet). Multi-Label: ein Titel kann mehrere Tags tragen.

export const TAGS = [
  // ---------- Sprachen / Länder ----------
  { id: "russisch", label: "Russisch", group: "Sprachen",
    patterns: ["russisch", "russian", "russland", "RU-"] },
  { id: "ukrainisch", label: "Ukrainisch", group: "Sprachen",
    patterns: ["ukrain"] },
  { id: "polnisch", label: "Polnisch", group: "Sprachen",
    patterns: ["polnisch", "polish", "polen", "polska"] },
  { id: "tschechisch", label: "Tschechisch", group: "Sprachen",
    patterns: ["tschech", "czech", "prag ", " prager"] },
  { id: "slowakisch", label: "Slowakisch", group: "Sprachen",
    patterns: ["slowak", "slovak"] },
  { id: "suedslavisch", label: "Südslavisch", group: "Sprachen",
    patterns: ["bosni", "kroati", "serb", "slowen", "sloven", "balkan", "jugoslaw",
      "sarajevo", "belgrad", "zagreb", "ljubljana", "makedon", "montenegro"] },
  { id: "sorbisch", label: "Sorbisch", group: "Sprachen",
    patterns: ["sorb"] },
  { id: "bulgarisch", label: "Bulgarisch", group: "Sprachen",
    patterns: ["bulgar"] },
  { id: "weissrussisch", label: "Weißrussisch", group: "Sprachen",
    patterns: ["weissruss", "weißruss", "belarus", "belarusian"] },
  { id: "kirchenslavisch", label: "Kirchenslavisch", group: "Sprachen",
    patterns: ["kirchenslav", "altkirchen"] },

  // ---------- Themen ----------
  { id: "krieg", label: "Krieg & Konflikt", group: "Themen",
    patterns: ["krieg", " war ", "воин", "воен", " front ", "besatz"] },
  { id: "erinnerung", label: "Erinnerung & Gedächtnis", group: "Themen",
    patterns: ["erinner", "memory", "gedachtnis", "gedächtnis", "memoria", "памят"] },
  { id: "identitaet", label: "Identität", group: "Themen",
    patterns: ["identit", "identity"] },
  { id: "korpora", label: "Korpora", group: "Themen",
    patterns: ["korpus", "corpus", "korpora", "corpora"] },
  { id: "digital", label: "Digitalität & KI", group: "Themen",
    patterns: ["digital", "künstliche intelligenz", "maschinell", " llm", "chatgpt",
      "algorithmus", "computational", "digitale"] },
  { id: "didaktik", label: "Didaktik & Unterricht", group: "Themen",
    patterns: ["didakt", "unterricht", "lehrwerk", "curriculum", "sprachvermittlung",
      "fremdsprachen", "fremdsprach", "daz", "daf", "lehramt", "daa"] },
  { id: "oekologie", label: "Ökologie & Natur", group: "Themen",
    patterns: ["okolog", "ecolog", "natur", "umwelt", "klima", "energie", "tschernobyl"] },
  { id: "exil", label: "Exil & Migration", group: "Themen",
    patterns: ["exil", "emigrat", "flucht", "vertrieb", "zwangsmigr", "displacement", "deport"] },
  { id: "film", label: "Film & Kino", group: "Themen",
    patterns: ["film", "kino", "cinema", "cine", "leinwand", "regie", "dokumentar"] },
  { id: "medien", label: "Medien", group: "Themen",
    patterns: ["medien", "media", "fernseh", "video", "podcast", "hörspiel", "hoerspiel", "audio"] },
  { id: "popkultur", label: "Popkultur", group: "Themen",
    patterns: ["pop", "musik", "comic", "fandom", "hip-hop", "hiphop", "serie", "jugend",
      "punk", "rock ", "lied", "song", " meme"] },
  { id: "translation", label: "Translation", group: "Themen",
    patterns: ["übersetz", "ubersetz", "translation", "dolmetsch", "переклад", "перевод"] },
  { id: "utopie", label: "Utopie & Dystopie", group: "Themen",
    patterns: ["utop", "dystop", "science fiction", "fantasy", "zukunft"] },
  { id: "sowjetismus", label: "(Post-)Sowjetisches", group: "Themen",
    patterns: ["sowjet", "soviet", "udssr", "cccp"] },
  { id: "grammatik", label: "Grammatik & Struktur", group: "Themen",
    patterns: ["syntax", "morpholog", "semantik", "phonolog", "phonetik", "lexik",
      "phraseolog", "grammatik", "kasus", "aspekt", "wortbildung"] },
  { id: "variation", label: "Mehrsprachigkeit & Variation", group: "Themen",
    patterns: ["mehrsprach", "herkunftssprach", "multiling", "variat", "sprachkontakt",
      "sprachpolitik", "minorit", "sprachwandel", "kontaktlinguistik"] },
  { id: "epochen", label: "Literaturgeschichte & Epochen", group: "Themen",
    patterns: ["jahrhundert", "avantgarde", "moderne", "realismus", "romantik", "barock",
      "aufklärung", "postmodern", "literaturgeschicht"] },
];

export const TAG_BY_ID = Object.fromEntries(TAGS.map((t) => [t.id, t]));
